# Generated by Django 6.0.7 on 2026-07-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='core.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario por Sucursal',
                'verbose_name_plural': 'Inventarios por Sucursales',
                'db_table': 'inventario_sucursales',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
