# Generated by Django 6.0.7 on 2026-07-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_options_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_desde', models.DateTimeField(auto_now_add=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inventario.producto')),
            ],
            options={
                'db_table': 'historial_precios',
                'ordering': ['-fecha_desde'],
            },
        ),
    ]
