# Generated by Django 6.0.7 on 2026-07-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_historialprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialprecio',
            name='precio_costo',
        ),
    ]
