# Generated by Django 6.0.7 on 2026-08-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_historialprecio_precio_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre', 'marca'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
