# Generated by Django 6.0.7 on 2026-08-03 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('core', '0001_initial'),
        ('inventario', '0004_remove_historialprecio_precio_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En Curso (Carrito)'), ('COMPLETADA', 'Cobrada y Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito)'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO_QR', 'Mercado Pago / QR'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_realizadas', to='clientes.cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'ventas_detalles',
            },
        ),
    ]
