# Generated by Django 6.0.7 on 2026-08-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO_QR', 'Mercado Pago / QR'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
