# Generated by Django 6.0.7 on 2026-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO_QR', 'Mercado Pago / QR'), ('CUENTA_CORRIENTE', 'Cuenta Corriente')], default='EFECTIVO', max_length=20),
        ),
    ]
