# Generated by Django 6.0.7 on 2026-08-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('BILLETERA_VIRTUAL', 'Billetera Virtual / QR'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('OTROS', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'ventas_pagos',
            },
        ),
    ]
