# Generated by Django 6.0.7 on 2026-08-05 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora del último cierre anterior')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tarjeta_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tarjeta_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_mercado_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_recaudado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('efectivo_usado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('efectivo_declarado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to='core.sucursal')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el cierre', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'cierre_caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
