# Generated by Django 6.0.7 on 2026-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_otros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
