# Generated by Django 6.0.7 on 2026-08-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cierrecaja_total_otros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierrecaja',
            old_name='total_mercado_pago',
            new_name='total_billetera_virtual',
        ),
    ]
