# Generated by Django 6.0.7 on 2026-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('CUIT', 'CUIT'), ('PASAPORTE', 'PASAPORTE')], default='DNI', max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
