# Generated by Django 6.0.7 on 2026-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_saldo_cuenta_corriente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuentacorriente',
            name='tipo',
            field=models.CharField(choices=[('DEUDA', 'Deuda por Venta'), ('PAGO', 'Entrega a Cuenta')], max_length=10),
        ),
    ]
