# Generated by Django 6.0.7 on 2026-08-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_movimientocuentacorriente_tipo'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO_PAGO_QR', 'Mercado Pago / QR')], default='EFECTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal'),
        ),
    ]
