# Generated by Django 6.0.7 on 2026-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_movimientocuentacorriente_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuentacorriente',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta Débito'), ('CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('BILLETERA_VIRTUAL', 'Billetera Virtual / QR'), ('OTROS', 'Otros')], default='EFECTIVO', max_length=50),
        ),
    ]
