# Generated by Django 6.0.7 on 2026-08-27 05:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_movimientocuentacorriente_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo_cuenta_corriente',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
