# Generated by Django 6.0.7 on 2026-07-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Borrador (Sin ingresar)'), ('COMPLETADA', 'Completada (Stock Sumado)')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
