# Generated by Django 6.0.7 on 2026-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(choices=[('CUIT', 'CUIT'), ('CUIL', 'CUIL'), ('DNI', 'DNI')], default='CUIT', max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rubro', models.CharField(help_text='Ej: Informática, Limpieza, Mercadería', max_length=100)),
                ('cbu_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE_30', 'Cheque a 30 días'), ('CHEQUE_60', 'Cheque a 60 días'), ('CHEQUE_90', 'Cheque a 90 días'), ('CUENTA_CORRIENTE', 'Cuenta Corriente')], default='TRANSFERENCIA', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
