# Generated by Django 6.0.7 on 2026-07-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='condicion_pago',
        ),
    ]
