# Generated by Django 6.0.7 on 2026-07-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(blank=True, help_text='Ej: Informática, Limpieza, Mercadería', max_length=100, null=True),
        ),
    ]
