# Generated by Django 6.0.7 on 2026-07-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_rubro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
