# Generated by Django 6.0.7 on 2026-07-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
